## Policy Step

pipeline:
  stages:
  - steps:
    - action:
        uses: harness/opa
        with:
          type: custom
          policy-set: namespace-validator #policy set name
          payload: "{name: <+infra.name>}"
          timeout: 10m
         


